#!/bin/sh

cd /dev
mknod mum0 c 126 0
mknod em8xxx0 c 127 0
mknod ir c 254 0
mknod led_rst c 253 0
ln -s ir irda

logger Inserting the modules...
echo "Inserting the modules..."
if [ "`egrep -i '^DISABLEOPTICAL=NO' /conf/config`" != "" ] &&
   [ "`egrep -i '^DISABLEOPTICAL=YES' /conf/config`" == "" ] ||
   [ "`egrep -i '^WDLXTV=OFF' /conf/config`" == "" ] ; then
	modprobe sr_mod
fi

insmod -f /lib/modules/llad.ko
insmod -f /lib/modules/proc_pipe.ko
export EM8XXX_SERVER=":0"
xrpc -u
xrpc -z
xrpc /lib/firmware/xrpc_xload_audio_ucode_SMP8634_*_facsprod.mips.nodts.bin
xrpc /lib/firmware/xrpc_xload_video_ucode_SMP8634_*_facsprod.mips.bin
xrpc /lib/firmware/xrpc_xload_demux_ucode_SMP8634_*_facsprod.mips.bin
xrpc /lib/firmware/xrpc_xload_irq_handler_SMP8634_*_facsprod.mips.bin
xrpc -ustart 2 4
xrpc -ustart 1 0
xrpc -ustart 1 1
xrpc -ustart 0 2
xrpc -ustart 0 3
insmod -f /lib/modules/em8xxx.ko

